#!/bin/bash

if dpkg-query --show "${PACKAGES[@]}"; then
    return 0
fi

required-target root || return 1
package-prepare-install || return 1
apt-get update || return 1
apt-get install -y "${PACKAGES[@]}" || return 1
if [[ $(type -t package-after-install) == "function" ]]; then
    package-after-install || return 1
fi
return 0
