#!/bin/bash

if dpkg-query --show "${PACKAGES[@]}"; then
    return 0
fi

required-target root
package-prepare-install || exit 1
apt-get update || exit 1
apt-get install -y "${PACKAGES[@]}" || exit 1
[[ $(type -t package-after-install) == "function" ]] && package-after-install
