#!/bin/bash

required-target user/miniconda || return 1

cat > ~/.condarc << EOF
channels:
  - defaults
show_channel_urls: true
default_channels:
  - https://mirrors.scut-smil.cn/anaconda/pkgs/main
  - https://mirrors.scut-smil.cn/anaconda/pkgs/r
  - https://mirrors.scut-smil.cn/anaconda/pkgs/msys2
custom_channels:
  conda-forge: https://mirrors.scut-smil.cn/anaconda/cloud
  msys2: https://mirrors.scut-smil.cn/anaconda/cloud
  bioconda: https://mirrors.scut-smil.cn/anaconda/cloud
  menpo: https://mirrors.scut-smil.cn/anaconda/cloud
  pytorch: https://mirrors.scut-smil.cn/anaconda/cloud
  simpleitk: https://mirrors.scut-smil.cn/anaconda/cloud
EOF
