#!/bin/bash

CONDA_BIN="$HOME/miniconda3/bin"

if [[ ! -f "$CONDA_BIN/conda" ]]
then
    wget https://mirrors.tuna.tsinghua.edu.cn/anaconda/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda3.sh || return 1
    chmod +x miniconda3.sh
    ./miniconda3.sh -b || return 1
    "$CONDA_BIN/conda" init || return 1
    rm miniconda3.sh
fi

echo Activating conda enviroment
. "$CONDA_BIN/activate" base || return 1
which python
