#!/bin/bash

CONDA_BIN="$HOME/miniconda3/bin"

if [[ ! -f "$CONDA_BIN/conda" ]]
then
    CONDA_INSTALLER="$HOME/miniconda3.sh"
    wget https://mirrors.scut-smil.cn/anaconda/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $CONDA_INSTALLER || return 1
    chmod +x $CONDA_INSTALLER
    $CONDA_INSTALLER -b || return 1
    "$CONDA_BIN/conda" init || return 1
    rm $CONDA_INSTALLER
fi

echo Activating conda enviroment
. "$CONDA_BIN/activate" base || return 1
which python
