#!/bin/bash

wget https://mirrors.tuna.tsinghua.edu.cn/anaconda/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda3.sh
chmod +x miniconda3.sh
./miniconda3.sh -b
./miniconda/bin/conda init
rm miniconda3.sh
