#!/bin/bash

required-target nvidia-docker || return 1

. utils/docker || return 1

NAME="gpu-board-server"
IMAGE="huww98/gpu-board-server:deploy"

remove-container-if-exists $NAME 

docker pull $IMAGE
docker run --detach --runtime nvidia --pid host \
    --name $NAME \
    --restart always \
    --volume /etc/passwd:/etc/passwd:ro \
    --publish 8000:8000 \
    --label=com.centurylinklabs.watchtower.enable=true \
    $IMAGE
