#!/bin/bash
required-target docker
required-target nvidia-driver

PACKAGES=(nvidia-docker2)

package-prepare-install() {
    curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
    distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
    curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list > /etc/apt/sources.list.d/nvidia-docker.list
}

package-after-install() {
    systemctl restart docker.service
}

. utils/package-target nvidia-docker
