#!/bin/bash
required-target docker || return 1
required-target nvidia-driver || return 1

PACKAGES=(nvidia-docker2)

package-prepare-install() {
    curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add - || return 1
    distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
    curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list > /etc/apt/sources.list.d/nvidia-docker.list || return 1
}

package-after-install() {
    systemctl restart docker.service
}

. utils/package-target nvidia-docker || return 1
